Make importable while preserving scripts.
Technically, setup.py should look like the following.

    py_modules=['smux'],
    entry_points={
        'console_scripts': ['smux.py=smux:main']
    }

Unfortunately, the auto-generated script smux.py causes a circular
dependency, resulting in the following error.

 ImportError: cannot import name 'main' from partially initialized
 module 'smux' (most likely due to a circular import)
 (/usr/local/bin/smux.py)

Since I cannot change the `smux.py` external name without breaking
various bash scripts depending on this script, this commit uses the hack
of specifying both `scripts` and `py_modules` in the setup call.